apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: caller-service
build:
  artifacts:
  - image: piomin/caller-service
    buildpacks:
      builder: paketobuildpacks/builder:tiny
      env:
        - BP_BOOT_NATIVE_IMAGE=true
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - k8s/ksvc.yaml
profiles:
  - name: jib
    build:
      artifacts:
        - image: piomin/caller-service
          jib: {}
  - name: k8s-deploy
    manifests:
      rawYaml:
        - k8s/deployment.yaml