apiVersion: apps/v1
kind: Deployment
metadata:
  name: caller-service
  labels:
    app.openshift.io/runtime: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caller-service
  template:
    metadata:
      labels:
        app: caller-service
        app.openshift.io/runtime: spring-boot
    spec:
      containers:
      - name: caller
        image: piomin/caller-service
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: caller-service
  labels:
    app.openshift.io/runtime: spring-boot
spec:
  selector:
    app: caller-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
